"""First migration

Revision ID: 9fad4128e455
Revises: 
Create Date: 2024-04-13 15:07:22.986516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fad4128e455'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=254), nullable=False),
    sa.Column('words_qty', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=254), nullable=False),
    sa.Column('idf', sa.Float(precision=10, asdecimal=True, decimal_return_scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('word_file',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column('tf', sa.Float(precision=10, asdecimal=True, decimal_return_scale=6), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_file')
    op.drop_table('words')
    op.drop_table('files')
    # ### end Alembic commands ###
